print("Tom is working hard..........")
print("Tom is working hard..........")
print("Tom is working hard..........")
print("Tom is working hard..........")
print("Tom is working hard..........")
print("Tom is working hard..........")